# https://raw.githubusercontent.com/hbstack/site/main/config/_default/menus.en.yml

main:
  - name: Beginner
    identifier: beginner
    weight: 1
    params:
      icon:
        vendor: bs
        name: book
  # - name: Tags
  #   identifier: patterns
  #   weight: 1000
  #   params:
  #     icon:
  #       name: boxes
  #       #color: 'skyblue'
  #       className: text-primary

  - name: Intermediate
    identifier: intermediate
    weight: 2
    params:
      icon:
        vendor: bs
        name: book

  - name: Expert
    identifier: expert
    weight: 3
    params:
      icon:
        vendor: bs
        name: book

  - name: Specialty
    identifier: specialty
    weight: 4
    params:
      icon:
        vendor: bs
        name: book

