# see https://hugomods.com/en/docs/google-adsense/.
# google_adsense = 'ca-pub-XXXXXXXXXXXXXXXX' # Please make that the Google AdSense module was imported.

hb:
  sass_transpiler: libsass # dartsass or libsass (deprecated)